### PR TITLE
Update to include and strictly use NAT Gateways as a best practice for high-availability.

### PR DESCRIPTION
**Pull request by santiagocardenas**
Note: This update modifies the parameters of the template by removing unused ones.

Also includes other minor changes like using S3 endpoint in every region (as they're now supported) and changing Joins to Subs.

### CODE REVIEW

**Comment by sopel** [comment]
@santiagocardenas - is there any reason why this hasn't been merged yet?

It's a notable and welcome simplification when guiding 3rd party users, would be great to have this readily available (seems tow work just fine and has been trivial to add to our [fork](https://github.com/utoolitylabs/quickstart-aws-vpc/commits/utoolity) of course, required only minor merge conflict adjustments). Thanks!

**Comment by agamzn** [comment]
@sopel , This will be discussed in our internal engineering meeting this week. The blast radius on this is quite large, so we need to make sure we don't break every downstream dependency in the process. We appreciate your patience.

**Comment by santiagocardenas** [comment]
@agamzn is this being merged?

**Comment by vsnyc** [comment]
@santiagocardenas Hi Santiago, it is difficult to accommodate removing the KeyPairName and NATInstanceType parameters at this time. So I have marked those as deprecated but keeping them in for backwards compatibility. Passing any value to these two parameters will  be a no-op. Will merge this after testing.

**Pull request merged**
